### ISSUE TITLE
ERROR: Repository not found.

### ISSUE THREAD

**Issue by guochangjiang** [RosettaCommons/rosetta_clone_tools#10]
When I  attempt to run the get_rosetta.sh script,  it will display the following error message:

Please make sure you have the correct access rights
and the repository exists.
ERROR: Repository not found.
fatal: Could not read from remote repository.

**Comment by roccomoretti** [comment]
The Rosetta repositories are only available for people who are members of a RosettaCommons lab. (And thus the script is only useful for those people.)

If you're not a member of a RosettaCommons lab, you can get access to Rosetta from https://www.rosettacommons.org/software/license-and-download and associated pages.
