### ISSUE TITLE
get_rosetta.sh hanging

### ISSUE THREAD

**Issue by kjdalenberg** [RosettaCommons/rosetta_clone_tools#3]
I have a user who is attempting to run the get_rosetta.sh script, and it's hanging on one step as shown in a log file:

 ^[[0;32m....is now cloned.^[[0m
^[[0;34mConfiguring the pre-commit hook...^[[0m
^[[0;34mConfiguring the post-commit hook...^[[0m
^[[0;34mConfiguring the prepare-commit-msg hook...^[[0m
^[[0;34mConfiguring aliases...^[[0m
^[[0;34mConfiguring git colors...^[[0m
^[[0;34mConfiguring git push to only push the current branch...^[[0m

The script hangs on this last step and doesn't provide any additional useful output.  I cannot find errors in the Debian server's system logs either.  We are seeing this behavior on 2 Debian servers from at least 2 users.  

Any guidance on the problem is appreciated.

**Comment by roccomoretti** [comment]
@kjdalenberg Are you using https authentication?

If so, you need to enter your password for each of the repositories (main, tools, docs, demos) being cloned. You might have entered it for the first repo, but it's "hanging" waiting for the passwords for the rest of the repos. (They're the same, but the way the script is written means that each download needs its own password entry.) Unfortunately, the prompt for the password is being pushed off the screen by the output from the first repository downloads, so it's not clear that's what's happening.
